Repository 2110336-SoftwareEngineering2/sec1_InfraTech, pull requests merged in 2021-02, with the labels that each got.

#16 Frontend/feature/login page
  frontend/components/LoginForm.js
  frontend/pages/login.js
Labels: enhancement

#17 Frontend/feature/landing page
  frontend/components/Header.js
  frontend/components/Sider.js
  frontend/config/Sider.config.js
  frontend/public/logo.svg
  frontend/tailwind.config.js
Labels: enhancement

#18 Backend/feature/preference
  backend/init.sql
  backend/src/register/entities/preference.entity.ts
  backend/src/register/entities/trainee-profile.entity.ts
  backend/src/register/entities/trainer-profile.entity.ts
Labels: invalid

#19 Frontend/feature/register
  frontend/components/register/CreateAccountForm.js
  frontend/components/register/FillInformationForm.js
  frontend/components/register/SelectPreferencesForm.js
  frontend/components/register/SelectRoleForm.js
  frontend/components/register/index.js
  frontend/lib/step-form.js
  frontend/pages/register.js
Labels: enhancement

#21 Frontend/features/import font
  frontend/styles/globals.css
  frontend/tailwind.config.js
Labels: enhancement

#23 Frontend/features/register form (State management)
  frontend/components/register/CreateAccountForm.js
  frontend/components/register/FillInformationForm.js
  frontend/components/register/SelectPreferencesForm.js
  frontend/components/register/SelectRoleForm.js
Labels: enhancement, frontend

#25 Backend/feature/register
  backend/init.sql
  backend/src/entities/user.entity.ts
  backend/src/login/login.module.ts
  backend/src/login/login.service.ts
  backend/src/register/entities/trainee-profile.entity.ts
  backend/src/register/entities/trainer-profile.entity.ts
  backend/src/register/register.controller.ts
  backend/src/register/register.module.ts
  backend/src/register/register.service.ts
  backend/src/register/repositories/user.repository.ts
Labels: refactor

#26 Backend/feature/register
  backend/init.sql
  backend/src/register/entities/trainer.entity.ts
  backend/src/register/register.module.ts
  backend/src/register/register.service.ts
  backend/src/register/repositories/trainer.repository.ts
Labels: refactor

#27 Backend/feature/register
  backend/init.sql
  backend/src/register/entities/trainee.entity.ts
  backend/src/register/register.module.ts
  backend/src/register/register.service.ts
  backend/src/register/repositories/trainee.repository.ts
Labels: refactor

#28 Backend/feature/register
  backend/init.sql
  backend/src/entities/user.entity.ts
  backend/src/register/entities/trainee.entity.ts
  backend/src/register/entities/trainer.entity.ts
  backend/src/register/register.service.ts
  backend/src/register/repositories/trainee.repository.ts
  backend/src/register/repositories/trainer.repository.ts
  backend/src/register/repositories/user.repository.ts
Labels: refactor

#22 Frontend/feature/login page
  frontend/.env.development
  frontend/components/AppLayout.js
  frontend/components/Header.js
  frontend/config/RedirectCondition.config.js
  frontend/lib/useUser.js
  frontend/package.json
  frontend/pages/api/login.js
  frontend/pages/api/user.js
  frontend/pages/index.js
  frontend/pages/login.js
  frontend/yarn.lock
Labels: enhancement

#31 Backend/setup openapi
  backend/package.json
  backend/src/main.ts
  backend/src/register/dtos/register-form-dto.ts
  backend/src/register/register.controller.ts
  backend/yarn.lock
Labels: documentation

#30 Backend/feature/preference
  backend/src/app.module.ts
  backend/src/entities/user.entity.ts
  backend/src/preference/entities/preference.entity.ts
  backend/src/preference/preference.controller.ts
  backend/src/preference/preference.module.ts
  backend/src/preference/preference.service.ts
  backend/src/register/register.module.ts
  backend/src/register/register.service.ts
  backend/src/register/repositories/user.repository.ts
Labels: enhancement

#33 Frontend/feature/login page
  backend/docker-compose.development.yml
  backend/init.sql
  backend/src/main.ts
  backend/src/middlewares/auth.middleware.ts
  frontend/.env.development
  frontend/components/AppLayout.js
  frontend/components/Header.js
  frontend/config/Sider.config.js
  frontend/config/UserType.config.js
  frontend/lib/useUser.js
  frontend/pages/api/user.js
  frontend/pages/login.js
Labels: backend, enhancement, frontend

#34 Backend/feature/auth guard
  backend/src/guards/auth.guard.ts
  backend/src/middlewares/auth.middleware.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.service.ts
Labels: backend, enhancement

#37 Backend/feature/config
  backend/config/development.ts
  backend/config/production.ts
  backend/package.json
  backend/src/app.module.ts
  backend/src/login/login.service.ts
  backend/src/main.ts
  backend/src/middlewares/auth.middleware.ts
  backend/yarn.lock
Labels: backend, enhancement, refactor

#40 Backend/format code
  backend/src/app.module.ts
  backend/src/login/dtos/login-form-dto.ts
  backend/src/login/login.service.ts
  backend/src/middlewares/auth.middleware.ts
  backend/src/profile/dtos/trainee-profile-dto.ts
  backend/src/profile/dtos/trainer-profile-dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.service.ts
Labels: bug

#41 🐛 add comma
  backend/init.sql
Labels: wontfix

#42 Backend/feature/profile
  backend/src/middlewares/auth.middleware.ts
  backend/src/profile/dtos/trainee-profile-dto.ts
  backend/src/profile/dtos/trainer-profile-dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.service.ts
Labels: backend, refactor

#43 Backend/feature/role guard
  README.md
  backend/src/decorators/role.decorator.ts
  backend/src/guards/role.guard.ts
  backend/src/profile/profile.controller.ts
Labels: backend, enhancement

#39 Frontend/feature/login invalid
  frontend/components/Header.js
  frontend/components/LoginForm.js
  frontend/config/config.js
  frontend/lib/useUser.js
  frontend/pages/_app.js
  frontend/pages/login.js
  frontend/styles/globals.css
Labels: enhancement, frontend

#45 Backend/fix entities
  backend/package.json
  backend/src/entities/trainee.entity.ts
  backend/src/entities/trainer.entity.ts
  backend/src/entities/user.entity.ts
  backend/src/login/login.service.ts
  backend/src/profile/dtos/trainee-profile-dto.ts
  backend/src/profile/dtos/trainer-profile-dto.ts
  backend/src/profile/profile.service.ts
  backend/src/register/register.service.ts
  backend/src/register/repositories/trainee.repository.ts
  backend/src/register/repositories/trainer.repository.ts
  backend/yarn.lock
Labels: backend, bug

#46 Backend/feature/profile
  backend/src/profile/dtos/update-trainee-profile-dto.ts
  backend/src/profile/dtos/update-trainer-profile-dto.ts
  backend/src/profile/profile.controller.ts
  backend/src/profile/profile.module.ts
  backend/src/profile/profile.service.ts
Labels: backend, enhancement

#50 Frontend/feature/style registration flow
  frontend/components/CustomUpload.js
  frontend/components/SelectPreferencesInput.js
  frontend/components/SelectRoleInput.js
  frontend/components/SelectionCard.js
  frontend/components/register/CreateAccountForm.js
  frontend/components/register/FillInformationForm.js
  frontend/components/register/SelectPreferencesForm.js
  frontend/components/register/SelectRoleForm.js
  frontend/components/register/StepHeader.js
  frontend/pages/register.js
  frontend/tailwind.config.js
Labels: enhancement, frontend
